runtime: nodejs18

env_variables:
  NODE_ENV: "production"
  DB_PATH: "/tmp/fpl_auction.db"

automatic_scaling:
  min_instances: 0
  max_instances: 10

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10